name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      pg_major:
        description: 'PostgreSQL major version (e.g., 16, 15, etc.)'
        required: true
        default: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          build-args: |
            PG_MAJOR=${{ inputs.pg_major }}
          push: true
          tags: ${{ github.repository_owner }}/${{ github.repository }}:pg-${{ inputs.pg_major }}
