name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      pg_major:
        description: 'PostgreSQL major version (e.g., 16, 15, etc.)'
        required: true
        default: '16'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:pg-${{ inputs.pg_major }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          build-args: |
            PG_MAJOR=${{ inputs.pg_major }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
